// PDF progress report card — generated client-side with jsPDF (lazy-loaded
// from CDN only on demand, so it never weighs down first paint). Mirrors the
// "advisory PDF" idea from ADEWS, but for a student's own progress.

let _jsPDF = null;
async function loadJsPDF() {
  if (_jsPDF) return _jsPDF;
  const mod = await import('https://cdn.jsdelivr.net/npm/jspdf@2.5.2/dist/jspdf.es.min.js');
  _jsPDF = mod.jsPDF || mod.default?.jsPDF || mod.default;
  return _jsPDF;
}

const GREEN = [45, 122, 58], AMBER = [201, 138, 0], RED = [192, 57, 43], GREY = [120, 120, 120];

function masteryColor(pct) {
  if (pct >= 75) return GREEN;
  if (pct >= 50) return AMBER;
  return RED;
}

// data = { email, distinct, total, correct, accuracy, streak, last7, dueCount,
//          topics: [{topic, total, correct, pct}], generatedAt: Date }
export async function generateReportCard(data) {
  const jsPDF = await loadJsPDF();
  const doc = new jsPDF({ unit: 'mm', format: 'a4' });
  const W = 210;
  const M = 16;            // left/right margin
  let y = 0;

  // Header band
  doc.setFillColor(...GREEN);
  doc.rect(0, 0, W, 30, 'F');
  doc.setTextColor(255, 255, 255);
  doc.setFont('helvetica', 'bold'); doc.setFontSize(20);
  doc.text('MasterMaths', M, 14);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(12);
  doc.text('Progress Report Card', M, 22);
  doc.setFontSize(9);
  const dt = (data.generatedAt || new Date()).toLocaleDateString('en-ZA', { year: 'numeric', month: 'long', day: 'numeric' });
  doc.text(dt, W - M, 14, { align: 'right' });
  if (data.email) doc.text(String(data.email), W - M, 20, { align: 'right' });

  y = 42;
  doc.setTextColor(0, 0, 0);

  // Headline stats row
  const stats = [
    ['Practised', String(data.distinct)],
    ['Accuracy', `${data.accuracy}%`],
    ['Day streak', String(data.streak)],
    ['This week', String(data.last7)],
    ['Due review', String(data.dueCount)],
  ];
  const colW = (W - 2 * M) / stats.length;
  stats.forEach((s, i) => {
    const cx = M + colW * i + colW / 2;
    doc.setFont('helvetica', 'bold'); doc.setFontSize(18); doc.setTextColor(...GREEN);
    doc.text(s[1], cx, y, { align: 'center' });
    doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...GREY);
    doc.text(s[0].toUpperCase(), cx, y + 6, { align: 'center' });
  });
  doc.setTextColor(0, 0, 0); doc.setFontSize(9);
  doc.text(`${data.correct} of ${data.total} self-marked correct.`, M, y + 14);

  y += 24;
  doc.setDrawColor(220, 220, 220); doc.line(M, y, W - M, y); y += 10;

  // Topic mastery
  doc.setFont('helvetica', 'bold'); doc.setFontSize(13); doc.text('Topic mastery', M, y); y += 8;
  doc.setFont('helvetica', 'normal'); doc.setFontSize(10);

  const barX = M + 62, barW = 80, barH = 4.5;
  const topics = (data.topics || []).slice();      // already weakest-first
  if (!topics.length) {
    doc.setTextColor(...GREY);
    doc.text('No topics practised yet.', M, y);
    doc.setTextColor(0, 0, 0);
    y += 8;
  }
  for (const t of topics) {
    if (y > 270) { doc.addPage(); y = 20; }
    const name = t.topic.length > 34 ? t.topic.slice(0, 33) + '…' : t.topic;
    doc.setTextColor(0, 0, 0); doc.setFontSize(9);
    doc.text(name, M, y + barH);
    // track
    doc.setFillColor(235, 235, 235); doc.rect(barX, y, barW, barH, 'F');
    // fill
    doc.setFillColor(...masteryColor(t.pct)); doc.rect(barX, y, barW * (t.pct / 100), barH, 'F');
    // pct
    doc.setTextColor(60, 60, 60);
    doc.text(`${t.pct}%  (${t.correct}/${t.total})`, barX + barW + 4, y + barH);
    y += 9;
  }

  // Focus + footer
  y += 4;
  const focus = topics.find(t => t.total >= 2) || topics[0];
  if (focus) {
    doc.setFont('helvetica', 'bold'); doc.setFontSize(10); doc.setTextColor(...RED);
    doc.text(`Focus next on: ${focus.topic} (${focus.pct}%)`, M, y); y += 8;
  }
  doc.setFont('helvetica', 'italic'); doc.setFontSize(10); doc.setTextColor(...GREEN);
  doc.text('Master the condition. Master the paper.', M, 285);
  doc.setFont('helvetica', 'normal'); doc.setFontSize(8); doc.setTextColor(...GREY);
  doc.text('Generated by MasterMaths · DBE NSC Mathematics', W - M, 285, { align: 'right' });

  const stamp = (data.generatedAt || new Date()).toISOString().slice(0, 10);
  doc.save(`MasterMaths-Report-${stamp}.pdf`);
}
